- name: Create temp directory
  tempfile:
      state: directory
      suffix: "-powerline-fonts"
  register: create_temp_dir

- name: Clone fonts repo
  git:
      repo: https://github.com/powerline/fonts.git
      depth: 1
      dest: "{{ create_temp_dir.path }}"

- name: Install fonts
  shell: "{{ create_temp_dir.path }}/install.sh"

- name: Clean up
  file:
      path: "{{ create_temp_dir.path }}"
      state: absent

